# VolEsti (volume computation and sampling library)
# Copyright (c) 2012-2018 Vissarion Fisikopoulos
# Licensed under GNU LGPL.3, see LICENCE file

version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: medium
    steps:
       - checkout
       - run:
            sudo apt-get update || true;
            sudo apt-get install cmake lp-solve;
            rm -rf build;
            mkdir build;
            cd build;
            cmake -DDISABLE_NLP_ORACLES=ON ../test -D ENABLE_COVERGE:BOOL=TRUE;
            make;
            ctest -j8 --verbose;
            bash <(curl -s https://codecov.io/bash) 
